In [6]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


import numpy as np

l=[1,2,3,4,5]
arr=np.array(l)
arr
print("data type of arr is",arr.dtype)

data type of arr is int64


In [11]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [25]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

l=[2+3j,4+5j,5+6j]
arr=np.array(l)
print("arrar",arr)
arr.dtype

arrar [2.+3.j 4.+5.j 5.+6.j]


dtype('complex128')

In [27]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

l=[1,2,3,4,5]
arr=np.array(l)
a=arr.astype(np.float32)
a.dtype

dtype('float32')

In [59]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.23456789, 2.3456789, 3.456789], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

print("Original array (float64):", arr)
print("Converted array (float32):", arr_float32)

Original array (float64): [1.23456789 2.3456789  3.456789  ]
Converted array (float32): [1.2345679 2.3456788 3.456789 ]


In [60]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
# type

def array_attributes(arr):
    """
    Returns the shape, size, and data type of a NumPy array.
    :param arr: Input NumPy array.
    :return: Tuple containing (shape, size, data type).
    """
    shape = arr.shape
    size = arr.size
    data_type = arr.dtype
    return shape, size, data_type

# Example usage:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, data_type = array_attributes(my_array)

print("Shape:", shape)
print("Size:", size)
print("Data type:", data_type)


Shape: (2, 3)
Size: 6
Data type: int64


In [62]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dim(arr):
    dimension = arr.ndim
    return dimension
my_array = np.array([[1, 2, 3], [4, 5, 6]])
dimension=array_dim(my_array)
print('Dimension is',dimension)

Dimension is 2


In [63]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
# size in bytes.

def item_size_info(arr):
    
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size


my_array = np.array([1, 2, 3], dtype=np.int32)
item_size, total_size = item_size_info(my_array)

print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")


Item size: 4 bytes
Total size: 12 bytes


In [64]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    """
    Returns the strides (step sizes) of a NumPy array.
    :param arr: Input NumPy array.
    :return: Tuple containing the strides.
    """
    return arr.strides

# Example usage:
my_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array_strides(my_array)

print("Strides:", strides)

Strides: (12, 4)


In [69]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
# and strides of the array.

def shape_stride_relationship(arr):
    """
    Returns the shape and strides of a NumPy array.
    :param arr: Input NumPy array.
    :return: Tuple containing (shape, strides).
    """
    shape = arr.shape
    strides = arr.strides
    return shape, strides

# Example usage:
my_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape_result, strides_result = shape_stride_relationship(my_array)

print("Shape:", shape_result)
print("Strides:", strides_result)

Shape: (2, 3)
Strides: (12, 4)


In [70]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)
n=int(input("Enter the value of n"))
zeros_array=create_zeros_array(n)
print(f"zero array {zeros_array}")

Enter the value of n 5


zero array [0. 0. 0. 0. 0.]


In [75]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(a,b):
    return np.ones((a,b))
a=int(input("Enter the number of rows"))
b=int(input("Enter the number of cols"))
ones_matrix=create_ones_matrix(a,b)
print(f"ones matrix is {ones_matrix}")      

Enter the number of rows 5
Enter the number of cols 3


ones matrix is [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [79]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
# `step`.

def generate_range_array(start, stop, step):
    """
    Creates a NumPy array with a specified range.
    :param start: Starting value.
    :param stop: Ending value (exclusive).
    :param step: Step size.
    :return: NumPy array with the specified range.
    """
    return np.arange(start, stop, step)

# Example usage:
start_value = int(input("Enter the start Value"))
end_value = int(input("Enter the end Value"))
step_size = int(input("Enter the step Value"))
range_array = generate_range_array(start_value, end_value, step_size)
print("Range array:", range_array)

Enter the start Value 1
Enter the end Value 10
Enter the step Value 2


Range array: [1 3 5 7 9]


In [90]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
# (inclusive).

def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)
start = float(input("Enter the start Value as float"))
stop = float(input("Enter the end Value as float"))
num = int(input("Enter the space Value as integer"))
generated_array=generate_linear_space(start,stop,num)
print("generated array is ",generated_array)

Enter the start Value as float 1.1
Enter the end Value as float 9.9
Enter the space Value as integer 10


generated array is  [1.1        2.07777778 3.05555556 4.03333333 5.01111111 5.98888889
 6.96666667 7.94444444 8.92222222 9.9       ]


In [99]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)
n=int(input("Enter the value of n"))
identity_matrix=create_identity_matrix(n)
print(f"The identity matrix of n x n size is {identity_matrix}")

Enter the value of n 5


The identity matrix of n x n size is [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [113]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

def list_to_array(l):
    return np.array(l)

l=list((input("Enter the elements of list seperated by comma")).split(","))
arr=list_to_array(l)
print("The numpy array is",arr)

Enter the elements of list seperated by comma 55,65,5,8,9


The numpy array is ['55' '65' '5' '8' '9']


In [115]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
# same data.

original_array = np.array([10, 20, 30, 40, 50])

# Display the original array
print("Original array:")
print(original_array)

# Create a view of the original array
view_array = original_array.view()

# Modify the view array (this will also affect the original array)
view_array[0] = 99

# Display the view array
print("\nView array (modified):")
print(view_array)

# Display the original array (notice the change)
print("\nOriginal array (after modification via view):")
print(original_array)


Original array:
[10 20 30 40 50]

View array (modified):
[99 20 30 40 50]

Original array (after modification via view):
[99 20 30 40 50]


In [133]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concat_two_array(arr1,arr2,shape):
    return np.concatenate((arr1, arr2), axis=axis)
arr1=np.array((1,2,3,4,5))
arr2=np.array((5,6,7,8,9))
axis=0
a=concat_two_array(arr1,arr2,shape)
print("Concatenated array ",a)

Concatenated array  [1 2 3 4 5 5 6 7 8 9]


In [136]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
# concatenate`.

array1 = np.array([[1, 2, 3], [4, 5, 6]]) 
array2 = np.array([[7, 8], [9, 10]])       

concatenated_result = np.concatenate((array1, array2), axis=1)

print("Concatenated array (horizontally):")
print(concatenated_result)



Concatenated array (horizontally):
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [2]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack(arrays):

    return np.vstack(arrays)

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

array3 = np.array([[13, 14, 15],
                   [16, 17, 18]])

# List of arrays
arrays_list = [array1, array2, array3]

# Stack arrays vertically
result = vertical_stack(arrays_list)

print("Stacked Array:")
print(result)


Stacked Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [8]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size.

def create_integer_array(start, stop, step):
   
    return np.arange(start, stop + 1, step, dtype=int)

start=int(input("Enter the start value"))
stop=int(input("Enter the stop value"))
step=int(input("Enter the sept"))

arr1 = create_integer_array(start,stop,step)
print(arr1)


Enter the start value 1
Enter the stop value 10
Enter the sept 1


[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
# (inclusive).

def create_array(star,stop,space):
    return np.linspace(start,stop,space)

start=int(input("Enter the start value"))
stop=int(input("Enter the stop value"))
space=int(input("Enter the sept"))

arr1 = create_array(start,stop,space)
print(arr1)


Enter the start value 0
Enter the stop value 1
Enter the sept 10


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
# 1000 (inclusive).

def create_array(star,stop,num):
    return np.logspace(np.log10(start),np.log10(stop),num)

start=int(input("Enter the start value"))
stop=int(input("Enter the stop value"))
num=int(input("Enter the num value"))

arr1 = create_array(start,stop,num)
print(arr1)

Enter the start value 1
Enter the stop value 1000
Enter the num value 5


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [2]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.

import pandas as pd

random_array=np.random.randint(1,101,(5,3))

df=pd.DataFrame(random_array,columns=['column1','column2','column2'])
df

column1  column2  column2
0       73       30       59
1       34       33       77
2       75       40       21
3       34       99       50
4       91       75       52

In [3]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negative_with_zero(df, column_name):
    # Use NumPy's where function to replace negative values with zero
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df


# Example DataFrame
data = {'A': [1, -2, 3, -4, 5],
        'B': [10, -20, 30, 40, -50]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'B' with zeros
df_modified = replace_negative_with_zero(df, 'B')

print("\nDataFrame after modification:")
print(df_modified)

Original DataFrame:
   A   B
0  1  10
1 -2 -20
2  3  30
3 -4  40
4  5 -50

DataFrame after modification:
   A   B
0  1  10
1 -2   0
2  3  30
3 -4  40
4  5   0


In [6]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

arr[2]

30

In [9]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

In [12]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

a=arr>5
result=arr[a]
print(result)

[ 8 10  7]


In [14]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1:5]

array([2, 3, 4, 5])

In [16]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_indices = [0, 1]
col_indices = [1, 2]

sub_array = arr_2d[row_indices][:, col_indices]

print(sub_array)

[[2 3]
 [5 6]]


In [17]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another array.

def extract_elements(arr_2d, indices):
   
   
    flat_arr = arr_2d.flatten()
    
 
    extracted_elements = flat_arr[indices]
    
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([1, 5, 7, 2, 3, 0])

result = extract_elements(arr_2d, indices)
print(result)

[2 6 8 3 4 1]


In [20]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
# boolean indexing.

def filter_greater_than_threshold(arr, threshold):
   
    mask = arr > threshold
    
   
    filtered_array = arr[mask]
    
    return filtered_array

arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5

result = filter_greater_than_threshold(arr, threshold)
print(result)

[ 8 10  7]


In [21]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
# separate arrays for each dimension.

def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
   
    extracted_elements = arr_3d[indices_dim1, indices_dim2, indices_dim3]
    
    return extracted_elements


arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10, 11, 12]]])

indices_dim1 = np.array([0, 1])     # Indices for the first dimension (depth)
indices_dim2 = np.array([0, 1])     # Indices for the second dimension (rows)
indices_dim3 = np.array([1, 2])     # Indices for the third dimension (columns)

result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print(result)

[ 2 12]


In [25]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing.

def elements_satisfying_conditions(arr, condition1, condition2):
    
    mask = (condition1) & (condition2)
    
   
    filtered_elements = arr[mask]
    
    return filtered_elements


arr = np.array([3, 8, 2, 10, 5, 7])
condition1 = arr > 4     # Elements greater than 4
condition2 = arr < 8     # Elements less than 8

result = elements_satisfying_conditions(arr, condition1, condition2)
print(result)

[5 7]


In [26]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays.

def extract_elements_2d(arr_2d, row_indices, col_indices):
   
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])    # Row indices
col_indices = np.array([1, 2, 0])    # Column indices

result = extract_elements_2d(arr_2d, row_indices, col_indices)
print(result)

[2 6 7]


In [52]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr=np.ones((3,3))
arr+5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [61]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[2, 3, 4]])


arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

arr1_broadcast = arr1.reshape(3, 1) 

result = arr1_broadcast * arr2

print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [67]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting.



arr1 = np.array([[1, 2, 3]])


arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])


result = arr1 + arr2

# Display the result
print("Result:")
print(result)


Result:
[[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


In [68]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
# broadcasting.


arr1 = np.array([[1],
                 [2],
                 [3]])


arr2 = np.array([[10, 20, 30]])


result = arr1 + arr2

print("Result:")
print(result)


Result:
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [72]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])


arr2 = np.array([[2, 3],
                 [4, 5]])


arr2_reshaped = arr2[:, :, np.newaxis]

result = arr1 * arr2_reshaped

print(result)

[[[ 2  4  6]
  [12 15 18]]

 [[ 4  8 12]
  [20 25 30]]]


In [73]:
# 41. Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])


arr = np.array([[1, 2, 3],
                [4, 5, 6]])


mean_columns = np.mean(arr, axis=0)

print(mean_columns)

[2.5 3.5 4.5]


In [74]:
# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])


arr = np.array([[1, 2, 3],
                [4, 5, 6]])


max_values = np.max(arr, axis=1)

print("Maximum values in each row:", max_values)


Maximum values in each row: [3 6]


In [75]:
# 43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[1, 2, 3],
                [4, 5, 6]])


max_indices = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:", max_indices)

Indices of maximum value in each column: [1 1 1]


In [76]:
# 44. For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])


arr = np.array([[1, 2, 3],
                [4, 5, 6]])


def moving_sum(row):
    cumsum = np.cumsum(row) 
    return cumsum


moving_sums = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Moving sums along rows:")
print(moving_sums)

Moving sums along rows:
[[ 1  3  6]
 [ 4  9 15]]


In [2]:
# 45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

arr = np.array([[2, 4, 6],
                [3, 5, 7]])


all_even_columns = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even?")
print(all_even_columns)


Are all elements in each column even?
[False False False]


In [3]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
# reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

original_array = np.array([1, 2, 3, 4, 5, 6])

# Specify the dimensions m and n
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array into m rows and n columns
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:")
print(reshaped_matrix)

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [5]:
# 47. Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


def flatten_matrix(matrix):
    return matrix.flatten()


input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


flattened_array = flatten_matrix(input_matrix)

print("Flattened array:")
print(flattened_array)

Flattened array:
[1 2 3 4 5 6]


In [14]:
# 48. Write a function that concatenates two given arrays along a specified axis.


array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)




concatenated_rows = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along rows:")
print(concatenated_rows)


concatenated_columns = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along columns:")
print(concatenated_columns)


Concatenated along rows:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def split_array(original_array, axis=0):
    return np.split(original_array, indices_or_sections=original_array.shape[axis], axis=axis)


original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


split_rows = split_array(original_array, axis=0)
print("Split along rows:")
for array in split_rows:
    print(array)


split_columns = split_array(original_array, axis=1)
print("\nSplit along columns:")
for array in split_columns:
    print(array)

Split along rows:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along columns:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [17]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements
    for idx, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, value)

    # Delete elements
    original_array = np.delete(original_array, indices_to_delete)

    return original_array



result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Resulting array after insertion and deletion:")
print(result_array)


Resulting array after insertion and deletion:
[ 1 10 11  4  5]


In [34]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.





arr1 = np.random.randint(low=1, high=100, size=5)

print("arr1 (random integers):")
print(arr1)

arr2 = np.random.randint(1, 11, size=5)

print("\narr2 (integers from 1 to 10):")
print(arr2)

result = arr1 + arr2

print("\nResult (element-wise addition):")
print(result)

arr1 (random integers):
[38 27 79 54 64]

arr2 (integers from 1 to 10):
[1 3 6 6 1]

Result (element-wise addition):
[39 30 85 60 65]


In [35]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.



arr1 = np.arange(10, 0, -1)


arr2 = np.arange(1, 11)


result_array = arr1 - arr2


print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result_array)


arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [43]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.



arr1 = np.random.randint(1, 10, size=(3, 3))  


arr2 = np.random.randint(1, 10, size=(3, 3))


result_array = arr1 * arr2[:, np.newaxis]  


print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result_array)


arr1:
[[2 5 5]
 [4 8 9]
 [7 3 8]]

arr2:
[[2 6 7]
 [1 9 1]
 [4 4 4]]

Result of element-wise multiplication:
[[[ 4 30 35]
  [ 8 48 63]
  [14 18 56]]

 [[ 2 45  5]
  [ 4 72  9]
  [ 7 27  8]]

 [[ 8 20 20]
  [16 32 36]
  [28 12 32]]]


In [44]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2, 11, 2)

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division between arr1 and arr2
result_array = arr1 / arr2

# Print the arrays and the result
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result_array)

arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [49]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.


arr1 = np.arange(1, 6)


arr2 = arr1[::-1]


result_array = arr1 ** arr2


print("arr1:")
print(arr1)
print("\narr2 (reversed arr1):")
print(arr2)
print("\nResult of element-wise exponentiation:")
print(result_array)


arr1:
[1 2 3 4 5]

arr2 (reversed arr1):
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [54]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])



def count_substring_occurrences(arr, substring):
    
    arr_list = arr.tolist()
  
    count = 0
    

    for string in arr_list:

        count += string.count(substring)
    
    return count


substring = 'hello'

occurrences = count_substring_occurrences(arr, substring)
print(f"Number of occurrences of '{substring}' in the array: {occurrences}")


Number of occurrences of 'hello' in the array: 3


In [61]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

import numpy as np

def extract_uppercase_characters(arr):
    
    arr_list = arr.tolist()
    
    
    uppercase_chars = []
    
   
    for string in arr_list:
      
        uppercase_chars.extend([char for char in string if char.isupper()])
    
    return np.array(uppercase_chars)



uppercase_chars = extract_uppercase_characters(arr)
print("Uppercase characters extracted:")
print(uppercase_chars)


Uppercase characters extracted:
['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [70]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])



def replace_substring(arr, old_substring, new_substring):
   
    arr_list = arr.tolist()
    
   
    modified_strings = []
 
    for string in arr_list:
       
        modified_string = string.replace(old_substring, new_substring)
        modified_strings.append(modified_string)
    
    return np.array(modified_strings)


old_substring = 'apple'
new_substring = 'orange'

modified_arr = replace_substring(arr, old_substring, new_substring)
print("Modified array:")
print(modified_arr)


Modified array:
['orange' 'banana' 'grape' 'pineorange']


In [71]:
# 59. Write a function that concatenates strings in a NumPy array element-wise
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])



def concatenate_strings(arr1, arr2):

    concatenated_arr = np.core.defchararray.add(arr1, arr2)
    
    return concatenated_arr



concatenated_arr = concatenate_strings(arr1, arr2)
print("Concatenated array:")
print(concatenated_arr)


Concatenated array:
['HelloOpen' 'WorldAI']


In [72]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])



def longest_string_length(arr):

    arr_list = arr.tolist()
    

    max_length = 0
    

    for string in arr_list:

        current_length = len(string)
        
   
        if current_length > max_length:
            max_length = current_length
    
    return max_length

max_length = longest_string_length(arr)
print("Length of the longest string in the array:", max_length)


Length of the longest string in the array: 9


In [73]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.

dataset = np.random.randint(1, 1001, size=100)

# Compute statistics
mean_value = np.mean(dataset)
median_value = np.median(dataset)
variance_value = np.var(dataset)
std_deviation_value = np.std(dataset)


print("Dataset:", dataset)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation_value)

Dataset: [113 349 668 477 115 451 205 730 595 340 938 612 320 296 670 889 537 500
 722 708 304 760 247 572  35  47 853 392  91 206 613 548 223 880 449 473
 981 759  54 564 278 801 819  43   9 738 115 602 894 373 452 474 305 656
 683 709 886 533 652 422 394 637 291 359 303 765 853 210  42 716 174 551
 174 423 292 339 986 369 801 628 263 547 955 180 851 293 726  53 818 465
  42 928  60 544 394  90  88 189 130  89]

Mean: 467.42
Median: 458.5
Variance: 76460.44359999998
Standard Deviation: 276.51481623956425


In [74]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
# dataset.

dataset = np.random.randint(1, 101, size=50)

# Compute percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

# Print the results
print("Dataset:", dataset)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset: [71 86 25 43 24 53 50 74  5 43 56 95 25 35 82 56 85 43 43 96 47  5 83 14
  1 21 55 17 63 88 76 39 52 44 84 67 46 44 37 15 30 32 91 89 92  9 75 74
 54 15]

25th Percentile: 30.5
75th Percentile: 74.75


In [75]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function


set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([2, 4, 6, 8, 10])


corr_matrix = np.corrcoef(set1, set2)


corr_coefficient = corr_matrix[0, 1]


print("Set 1:", set1)
print("Set 2:", set2)
print("\nCorrelation coefficient between Set 1 and Set 2:", corr_coefficient)


Set 1: [1 2 3 4 5]
Set 2: [ 2  4  6  8 10]

Correlation coefficient between Set 1 and Set 2: 0.9999999999999999


In [77]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function


matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])


result_matrix = np.dot(matrix1, matrix2)


print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result_matrix)



Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [78]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles.


dataset = np.random.randint(10, 1001, size=50)


percentile_10 = np.percentile(dataset, 10)
percentile_50 = np.percentile(dataset, 50)  # Median
percentile_90 = np.percentile(dataset, 90)
quartile_1 = np.percentile(dataset, 25)
quartile_3 = np.percentile(dataset, 75)


print("Dataset:", dataset)
print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("1st Quartile:", quartile_1)
print("3rd Quartile:", quartile_3)


Dataset: [751 154 698 666 675 403 910 619 111 611 873 690 736 788 690 515 772 983
 255 376 221 804 893 698 176 646 134 765  28 350 880 598 582  90 449 481
 617 643 935 817 464 315 870 537  19 270 308 254 813 363]

10th Percentile: 152.0
50th Percentile (Median): 614.0
90th Percentile: 873.7
1st Quartile: 323.75
3rd Quartile: 761.5


In [79]:
# 66. Create a NumPy array of integers and find the index of a specific element.

arr = np.array([10, 20, 30, 40, 50])


element_to_find = 30

index = np.where(arr == element_to_find)[0]

print("Array:", arr)
print("Index of element", element_to_find, ":", index)

Array: [10 20 30 40 50]
Index of element 30 : [2]


In [80]:
# 67. Generate a random NumPy array and sort it in ascending order.


random_array = np.random.rand(10) 
print("Random Array (Floats):", random_array)

sorted_array = np.sort(random_array)
print("Sorted Array (Floats):", sorted_array)


Random Array (Floats): [0.80125777 0.51292921 0.99617444 0.26292965 0.68426657 0.1134504
 0.06250049 0.7651008  0.43541382 0.10780494]
Sorted Array (Floats): [0.06250049 0.10780494 0.1134504  0.26292965 0.43541382 0.51292921
 0.68426657 0.7651008  0.80125777 0.99617444]


In [81]:
# 68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])


arr = np.array([12, 25, 6, 42, 8, 30])


filtered_array = arr[arr > 20]


print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_array)


Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [82]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])



filtered_array = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_array)


Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [84]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

filtered_array = arr[(arr >= 20) & (arr <= 40)]
print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_array)

Original Array: [10 20 30 40 50]
Filtered Array (elements divisible by 3): [20 30 40]


In [7]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print(f"The byte order of the array is: {byte_order}")

The byte order of the array is: =


In [10]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(True)

print("Modified array after byte swapping:")
print(arr)

Modified array after byte swapping:
[16777216 33554432 50331648]


In [11]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using
# `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder('S') 

print("Original array:")
print(arr)

print("\nSwapped array (new byte order):")
print(swapped_arr)


Original array:
[1 2 3]

Swapped array (new byte order):
[16777216 33554432 50331648]


In [12]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using
# `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original array:")
print(arr)

print("\nSwapped array (based on system endianness):")
print(swapped_arr)

Original array:
[1 2 3]

Swapped array (based on system endianness):
[16777216 33554432 50331648]


In [13]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
# attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

if byte_order == '=':
    print("Byte order matches native system byte order. No byte swapping needed.")
else:
    print("Byte order does not match native system byte order. Byte swapping may be necessary.")

Byte order matches native system byte order. No byte swapping needed.


In [18]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1=np.random.randint(1,10,10)
copy_arr=arr1.copy()
copy_arr[0]=100
print("Original_arr after modification in copy_arr",arr1)
print("Modified Copy_arr",copy_arr)

Original_arr after modification in copy_arr [6 1 9 2 1 7 4 4 9 3]
Modified Copy_arr [100   1   9   2   1   7   4   4   9   3]


In [19]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(1, 10, size=(3, 3))
print("Original matrix:")
print(matrix)

view_slice = matrix[1:, 1:]
print("\nView slice:")
print(view_slice)

view_slice[0, 0] = 100  

print("\nModified view slice:")
print(view_slice)

Original matrix:
[[8 5 9]
 [2 3 9]
 [6 5 4]]

View slice:
[[3 9]
 [5 4]]

Modified view slice:
[[100   9]
 [  5   4]]


In [21]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)
print("Original array_a:")
print(array_a)

view_b = array_a[2:, 1:]  
print("\nView slice (view_b):")
print(view_b)

view_b += 5

print("\nModified view_b:")
print(view_b)

print("\nOriginal array_a after modification in view_b:")
print(array_a)


Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

View slice (view_b):
[[ 8  9]
 [11 12]]

Modified view_b:
[[13 14]
 [16 17]]

Original array_a after modification in view_b:
[[ 1  2  3]
 [ 4  5  6]
 [ 7 13 14]
 [10 16 17]]


In [22]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.


orig_array = np.arange(1, 9).reshape(2, 4)
print("Original orig_array:")
print(orig_array)

reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped view (reshaped_view):")
print(reshaped_view)


reshaped_view[0, 0] = 100 

print("\nModified reshaped_view:")
print(reshaped_view)

print("\nOriginal orig_array after modification in reshaped_view:")
print(orig_array)

Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original orig_array after modification in reshaped_view:
[[100   2   3   4]
 [  5   6   7   8]]


In [23]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


data = np.random.randint(1, 10, size=(3, 4))
print("Original data:")
print(data)

data_copy = data[data > 5].copy()
print("\nCopy of elements greater than 5 (data_copy):")
print(data_copy)

data_copy[0] = 100  


print("\nModified data_copy:")
print(data_copy)

print("\nOriginal data after modification in data_copy:")
print(data)


Original data:
[[2 7 9 1]
 [4 5 9 8]
 [8 3 2 9]]

Copy of elements greater than 5 (data_copy):
[7 9 9 8 8 9]

Modified data_copy:
[100   9   9   8   8   9]

Original data after modification in data_copy:
[[2 7 9 1]
 [4 5 9 8]
 [8 3 2 9]]


In [24]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.


A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])


addition_result = A + B


subtraction_result = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition result (A + B):")
print(addition_result)

print("\nSubtraction result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


In [25]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

addition_result = A + B

subtraction_result = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition result (A + B):")
print(addition_result)

print("\nSubtraction result (A - B):")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


In [26]:
# 83. Create a matrix `E` and find its transpose.

E = np.array([[1, 2, 3],
              [4, 5, 6]])

# Find the transpose of matrix E
E_transpose = E.T

# Print matrix E and its transpose
print("Matrix E:")
print(E)

print("\nTranspose of matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of matrix E:
[[1 4]
 [2 5]
 [3 6]]


In [27]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the determinant of F
determinant_F = np.linalg.det(F)

# Print the matrix F and its determinant
print("Matrix F:")
print(F)

print("\nDeterminant of matrix F:")
print(determinant_F)

Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F:
0.0


In [28]:
# 85. Create a square matrix `G` and find its inverse.

G = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the inverse of G
try:
    G_inv = np.linalg.inv(G)
    print("Inverse of matrix G:")
    print(G_inv)
except np.linalg.LinAlgError:
    print("Matrix G is singular and its inverse does not exist.")

Matrix G is singular and its inverse does not exist.
